version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  webserver:
    image: nginx:alpine
    ports:
      - 8080:80
    networks:
      - web
      - internal
    volumes:
      - ./app:/public
      - ./app/nginx:/etc/nginx/conf.d
      - ./app/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - traefik.http.routers.webserver.rule=Host(`${URL}`)
      - traefik.http.routers.webserver.tls=true
      - traefik.http.routers.webserver.tls.certresolver=lets-encrypt
      - traefik.port=80
      - traefik.docker.network=web
    links:
      - php
  php:
    image: php:fpm-alpine
    volumes:
      - ./app:/public
    networks:
      - internal
